apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod1-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.15.5
        name: mypod1