kind: Pod
apiVersion: v1
metadata:
  name: mypod3
  namespace: pod-resource
spec:
  containers:
  - name: mypod3
    image: nginx:1.15.5
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 256Mi