apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: azd1
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: default
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: azd2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: default
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: azd3
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: default
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: azd4
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: default
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: azd5
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: default
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: azd6
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: default
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: azd7
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: default
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: azd8
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: default
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: azd9
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: default